### ISSUE TITLE
bm7 (x86_64 ABI struct on stack?)

### ISSUE THREAD

**Issue by numsim1415** [davmac314/ccomp-microbench#2]
Dear Davin,

reading
https://en.wikipedia.org/wiki/X86_calling_conventions#System_V_AMD64_ABI
it states that 

>[...] Integral return values up to 64 bits in size are stored in RAX while values up to 128 bit are stored in RAX and RDX. [...] If the callee wishes to use registers RBX, RBP, and R12–R15, it must restore their original values before returning control to the caller. All other registers must be saved by the caller if it wishes to preserve their values.[19]:16 [...] on function entry, the return address is adjacent to the seventh integer argument on the stack.

As far as I understand, this does not seem to be specific about how to return anything more than 128 bit int. Is this specified somewhere do clang and gcc "happen" to agree on how to handle this?
https://godbolt.org/g/12dVYK
I'd be curious and happy if you could point me to an explanation. Thank you in advance.

**Comment by davmac314** [comment]
Full details are in the System V ABI supplement for the AMD64 architecture as published by Intel: https://software.intel.com/sites/default/files/article/402129/mpx-linux64-abi.pdf

(See chapter 3.2).
